// Diff noise filter — port of the patterns from
// https://blog.cloudflare.com/ai-code-review/
//
// Don't waste tokens (or the model's attention) reviewing lockfiles,
// minified bundles, or generated source maps.

const NOISE_FILE_PATTERNS = [
  "bun.lock",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "Cargo.lock",
  "go.sum",
  "poetry.lock",
  "Pipfile.lock",
  "flake.lock"
];

const NOISE_EXTENSIONS = [".min.js", ".min.css", ".bundle.js", ".map"];

const GENERATED_MARKERS = [/@generated/i, /DO NOT EDIT/i, /This file is autogenerated/i];

export interface DiffFile {
  path: string;
  patch: string;
  addedLines: number;
  removedLines: number;
}

export function isNoiseFile(path: string): boolean {
  const base = path.split("/").pop() ?? path;
  if (NOISE_FILE_PATTERNS.includes(base)) return true;
  if (NOISE_EXTENSIONS.some((ext) => path.endsWith(ext))) return true;
  return false;
}

export function isGenerated(patch: string): boolean {
  // Scan only the first ~20 lines — the markers are always near the top.
  const head = patch.split("\n", 20).join("\n");
  return GENERATED_MARKERS.some((re) => re.test(head));
}

export function filterNoise(files: DiffFile[]): DiffFile[] {
  return files.filter((f) => {
    if (isNoiseFile(f.path)) return false;
    if (isGenerated(f.patch)) return false;
    return true;
  });
}

/**
 * Parse a unified diff (the raw text from
 * `Accept: application/vnd.github.v3.diff`) into per-file chunks with
 * added/removed line counts. This is a simple parser; not a full implementation
 * but plenty for what the reviewer needs.
 */
export function parseUnifiedDiff(diff: string): DiffFile[] {
  const files: DiffFile[] = [];
  const fileChunks = diff.split(/^diff --git /m).slice(1);

  for (const chunk of fileChunks) {
    const firstLine = chunk.split("\n", 1)[0]; // "a/path b/path"
    const m = firstLine.match(/b\/(\S+)/);
    if (!m) continue;
    const path = m[1];
    const patch = "diff --git " + chunk;

    let added = 0;
    let removed = 0;
    for (const line of chunk.split("\n")) {
      if (line.startsWith("+++") || line.startsWith("---")) continue;
      if (line.startsWith("+")) added++;
      else if (line.startsWith("-")) removed++;
    }
    files.push({ path, patch, addedLines: added, removedLines: removed });
  }

  return files;
}
